insert into category (id, parent_id, category_name, description) values (1, 1, 'dictumst etiam faucibus cursus', 'justo eu massa donec dapibus duis at velit');
insert into category (id, parent_id, category_name, description) values (2, 2, 'rutrum', 'ut massa quis augue luctus tincidunt nulla');
insert into category (id, parent_id, category_name, description) values (3, 3, 'nec nisi volutpat eleifend', 'nisl venenatis lacinia aenean');
insert into category (id, parent_id, category_name, description) values (4, 4, 'arcu sed augue aliquam erat', 'quam turpis adipiscing lorem vitae');
insert into category (id, parent_id, category_name, description) values (5, 5, 'vestibulum ante', 'justo pellentesque viverra pede ac diam cras pellentesque volutpat dui');
insert into category (id, parent_id, category_name, description) values (6, 6, 'phasellus id sapien in sapien', 'metus sapien ut nunc vestibulum ante ipsum primis in');
insert into category (id, parent_id, category_name, description) values (7, 7, 'sapien cum sociis natoque penatibus et magnis dis parturient montes', 'amet nulla quisque arcu libero rutrum ac');
insert into category (id, parent_id, category_name, description) values (8, 8, 'dolor vel est donec odio justo sollicitudin ut', 'eu interdum eu tincidunt in leo maecenas pulvinar');
insert into category (id, parent_id, category_name, description) values (9, 9, 'mi integer ac neque duis bibendum morbi', 'id pretium iaculis diam');
insert into category (id, parent_id, category_name, description) values (10, 10, 'sollicitudin mi', 'nec');
insert into category (id, parent_id, category_name, description) values (11, 11, 'a feugiat', 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede');
insert into category (id, parent_id, category_name, description) values (12, 12, 'congue', 'posuere cubilia curae');
insert into category (id, parent_id, category_name, description) values (13, 13, 'cras in purus eu', 'curae duis faucibus accumsan odio curabitur convallis duis');
insert into category (id, parent_id, category_name, description) values (14, 14, 'magna bibendum imperdiet nullam orci pede venenatis non sodales', 'pellentesque ultrices phasellus id');
insert into category (id, parent_id, category_name, description) values (15, 15, 'quisque id justo sit amet sapien', 'eu orci mauris lacinia sapien');
insert into category (id, parent_id, category_name, description) values (16, 16, 'nisl', 'neque');
insert into category (id, parent_id, category_name, description) values (17, 17, 'turpis adipiscing lorem vitae mattis nibh', 'nonummy maecenas');
insert into category (id, parent_id, category_name, description) values (18, 18, 'ut', 'suscipit');
insert into category (id, parent_id, category_name, description) values (19, 19, 'id pretium iaculis diam erat fermentum justo nec', 'proin at turpis a pede posuere nonummy');
insert into category (id, parent_id, category_name, description) values (20, 20, 'in', 'diam neque vestibulum eget');
