insert into product_language (id, product_language_name) values (1, 'ac neque duis bibendum morbi non quam nec dui');
insert into product_language (id, product_language_name) values (2, 'leo maecenas pulvinar lobortis est phasellus sit amet');
insert into product_language (id, product_language_name) values (3, 'ornare consequat lectus in est risus auctor');
insert into product_language (id, product_language_name) values (4, 'aliquet pulvinar sed nisl');
insert into product_language (id, product_language_name) values (5, 'nulla nisl nunc nisl duis');
insert into product_language (id, product_language_name) values (6, 'nulla suspendisse potenti cras in');
insert into product_language (id, product_language_name) values (7, 'accumsan tellus nisi eu orci');
insert into product_language (id, product_language_name) values (8, 'sociis');
insert into product_language (id, product_language_name) values (9, 'ante vel ipsum praesent blandit lacinia erat');
insert into product_language (id, product_language_name) values (10, 'enim lorem ipsum');
insert into product_language (id, product_language_name) values (11, 'quam sapien varius ut blandit non interdum');
insert into product_language (id, product_language_name) values (12, 'porttitor pede justo eu');
insert into product_language (id, product_language_name) values (13, 'mollis molestie lorem quisque ut erat curabitur gravida');
insert into product_language (id, product_language_name) values (14, 'tortor sollicitudin mi sit amet lobortis sapien sapien');
insert into product_language (id, product_language_name) values (15, 'sed lacus');
insert into product_language (id, product_language_name) values (16, 'viverra eget congue eget semper rutrum nulla nunc purus phasellus');
insert into product_language (id, product_language_name) values (17, 'blandit non interdum in ante vestibulum ante');
insert into product_language (id, product_language_name) values (18, 'sem fusce consequat');
insert into product_language (id, product_language_name) values (19, 'turpis adipiscing lorem vitae mattis nibh ligula');
insert into product_language (id, product_language_name) values (20, 'rhoncus aliquam');
