insert into serie (id, serie_name) values (1, 'purus aliquet at feugiat non');
insert into serie (id, serie_name) values (2, 'mauris laoreet');
insert into serie (id, serie_name) values (3, 'mauris sit amet');
insert into serie (id, serie_name) values (4, 'magnis dis parturient montes');
insert into serie (id, serie_name) values (5, 'nisl nunc rhoncus dui vel');
insert into serie (id, serie_name) values (6, 'id lobortis');
insert into serie (id, serie_name) values (7, 'habitasse platea');
insert into serie (id, serie_name) values (8, 'praesent id massa id');
insert into serie (id, serie_name) values (9, 'purus eu magna vulputate');
insert into serie (id, serie_name) values (10, 'tempus sit amet sem');
insert into serie (id, serie_name) values (11, 'eros suspendisse accumsan tortor quis');
insert into serie (id, serie_name) values (12, 'massa');
insert into serie (id, serie_name) values (13, 'elementum eu');
insert into serie (id, serie_name) values (14, 'rhoncus aliquam');
insert into serie (id, serie_name) values (15, 'neque aenean auctor gravida sem');
insert into serie (id, serie_name) values (16, 'vestibulum ante ipsum primis in');
insert into serie (id, serie_name) values (17, 'vestibulum ante ipsum primis');
insert into serie (id, serie_name) values (18, 'orci');
insert into serie (id, serie_name) values (19, 'nisi volutpat eleifend donec ut');
insert into serie (id, serie_name) values (20, 'condimentum id luctus nec');
