insert into taxe (id, taxe_name, taxe_value) values (1, 'luctus cum', 10);
insert into taxe (id, taxe_name, taxe_value) values (2, 'morbi quis', 16);
insert into taxe (id, taxe_name, taxe_value) values (3, 'semper', 94);
insert into taxe (id, taxe_name, taxe_value) values (4, 'at velit eu est congue', 32);
insert into taxe (id, taxe_name, taxe_value) values (5, 'nisl', 79);
insert into taxe (id, taxe_name, taxe_value) values (6, 'sollicitudin vitae consectetuer', 80);
insert into taxe (id, taxe_name, taxe_value) values (7, 'luctus et ultrices posuere', 68);
insert into taxe (id, taxe_name, taxe_value) values (8, 'pede ullamcorper augue a suscipit', 33);
insert into taxe (id, taxe_name, taxe_value) values (9, 'sed sagittis', 52);
insert into taxe (id, taxe_name, taxe_value) values (10, 'nisl ut volutpat sapien arcu', 65);
insert into taxe (id, taxe_name, taxe_value) values (11, 'at', 71);
insert into taxe (id, taxe_name, taxe_value) values (12, 'et ultrices posuere cubilia curae', 62);
insert into taxe (id, taxe_name, taxe_value) values (13, 'condimentum id luctus nec molestie', 75);
insert into taxe (id, taxe_name, taxe_value) values (14, 'leo pellentesque ultrices mattis', 83);
insert into taxe (id, taxe_name, taxe_value) values (15, 'odio donec', 20);
insert into taxe (id, taxe_name, taxe_value) values (16, 'ut odio cras mi', 21);
insert into taxe (id, taxe_name, taxe_value) values (17, 'at turpis donec posuere metus', 74);
insert into taxe (id, taxe_name, taxe_value) values (18, 'ut nulla sed', 8);
insert into taxe (id, taxe_name, taxe_value) values (19, 'quisque id justo sit', 43);
insert into taxe (id, taxe_name, taxe_value) values (20, 'elit ac nulla sed', 91);
